// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sorgabetaaltool.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.math.BigInteger;

public class TestIbanNumber extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String Iban;

	public TestIbanNumber(IContext context, java.lang.String Iban)
	{
		super(context);
		this.Iban = Iban;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return isIbanValid(this.Iban);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TestIbanNumber";
	}

	// BEGIN EXTRA CODE
	private boolean isIbanValid(String iban) {
		// remove spaces
		iban = iban.replace("\\s", "");
	
		// make all uppercase
		iban = iban.toUpperCase();
	
		// check length - complicated, depends on country. Skipping for now.
		// https://en.wikipedia.org/wiki/International_Bank_Account_Number#Structure
	
		// move first four letters to the end
		iban = iban.substring(4) + iban.substring(0,4);
	
		// convert letters to digits
		String total = "";
		for (int i = 0; i < iban.length(); i++) {
	
			int charValue = Character.getNumericValue(iban.charAt(i));
	
			if (charValue < 0 || charValue > 35) {
				return false;
			}
	
			total += charValue;
		}
	
		// Make BigInteger and check if modulus 97 is 1 
		
		BigInteger totalInt = new BigInteger(total);
		return totalInt.mod(new BigInteger("97")).equals(BigInteger.ONE);
	}
	// END EXTRA CODE
}
